steps:
  - id: Clone
    name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/learner-git/nginx_custom.git"]

  - id: Build
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "."

  - id: Tag Latest Stage
    name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"

  - id: Push
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"

timeout: 900s
