steps:
  - id: Build
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$(sha256sum Dockerfile | awk "{print $$1}")'
      - "."

  - id: Tag Latest Stage
    name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$(sha256sum Dockerfile | awk "{print $$1}")'
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"

  - id: Push
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$(sha256sum Dockerfile | awk "{print $$1}")'

timeout: 900s
